# Generated by Django 3.2.9 on 2022-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0003_firstsidenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='secondleft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondleft_title', models.CharField(max_length=100)),
                ('secondleft_image', models.FileField(default=None, max_length=250, null=True, upload_to='secondleft/')),
            ],
        ),
    ]
