# Generated by Django 3.2.9 on 2022-01-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0005_thirdfirst_thirdsecond'),
    ]

    operations = [
        migrations.CreateModel(
            name='fourth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fourth_image', models.FileField(default=None, max_length=250, null=True, upload_to='fourth/')),
            ],
        ),
    ]
