# Generated by Django 3.2.9 on 2022-01-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0006_fourth'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_title', models.CharField(max_length=50)),
            ],
        ),
    ]
