# Generated by Django 3.2.9 on 2022-01-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0009_auto_20220109_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
