# Generated by Django 3.2.9 on 2022-01-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0012_rename_suburb_userinfo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced')], default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mobile',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='title',
            field=models.CharField(blank=True, choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default=None, max_length=3, null=True),
        ),
    ]
