# Generated by Django 3.2.9 on 2022-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0013_auto_20220109_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced')], default='SINGLE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=100, null=True),
        ),
    ]
