# Generated by Django 3.2.9 on 2022-01-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0014_auto_20220109_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_birth',
            field=models.DateField(blank=True, default='Date Format - "YYYY-MM-DD" ', null=True),
        ),
    ]
