# Generated by Django 3.2.9 on 2022-01-09 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0017_alter_userinfo_date_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='sex',
            new_name='gender',
        ),
    ]
